# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11B9LwQ_wOdNysdbfuV0zbrdATGLeDX_g

**Task 07: Querying RDF(s)**
"""

!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "Person" with RDFLib and SPARQL**"""

from rdflib.plugins.sparql import prepareQuery

q1 = prepareQuery('''
  SELECT ?Sub
    WHERE{
      ?Sub rdfs:subClassOf <http://somewhere#Person>
    }
    '''
      )
for r in g.query(q1):
  print(r.Sub)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

q2 = prepareQuery('''
  SELECT ?Sub ?Person
    WHERE{
      ?Sub rdfs:subClassOf <http://somewhere#Person> .
      ?Person rdf:type <http://somewhere#Person> .
      }
      '''
      )
for r in g.query(q2):
  print(r.Sub, r.Person)

"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**

"""

q3 = prepareQuery('''
  SELECT ?Sub ?Person ?prop
    WHERE{
      ?Sub rdf:type <http://somewhere#Person> .
      ?Person ?porp ?z .
      }
      '''
      )
for r in g.query(q3):
  print(r.Sub, r.Person)